apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: mann-whitney
  namespace: argo-kapcom-test
spec:
  args:
  - name: start-time
  - name: end-time
  - name: stable-hash
  - name: canary-hash
  metrics:
  - name: mann-whitney
    provider:
      kayenta:
        address: http://kayenta-test.sandbox.cloud.adobe.io
        application: rollouts-demo-2
        canaryConfigName: my-test
        metricsAccountName: canary-prometheus
        storageAccountName: aws-kayenta
        configurationAccountName: abc
        threshold:
          pass: 90
          marginal: 75
        scopes:
        - name: default
          controlScope:
            scope: app=rollouts-demo-2 and rollouts-pod-template-hash={{args.stable-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
            region: "us-east-1"
          experimentScope:
            scope: app=rollouts-demo-2 and rollouts-pod-template-hash={{args.canary-hash}}
            step: 60
            start: "{{args.start-time}}"
            end: "{{args.end-time}}"
            region: "us-east-1"